# Generated by Django 2.0.5 on 2018-06-23 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180623_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Book'),
        ),
    ]
