# Generated by Django 2.0.5 on 2018-07-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180624_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='public',
            options={'verbose_name_plural': 'reshu'},
        ),
    ]
